
const INGREDIENTS = [
    "apple",
    "flour",
    "water",
    "leek",
    "dill",
    "green bean",
    "olive oil",
    "salt",
    "lemon",
    "sugar",
    "egg",
    "vanilla",
    "steak",
    "mirin",
    "sake",
    "soy sauce",
    "peach",
    "syrup",
    "potato",
    "bacon",
    "chive",
    "brussels sprouts",
    "shallot",
    "vinegar",
    "gravy",
    "rice",
    "lentil",
    "radish",
    "cauliflower",
    "vegetable oil",
    "black pepper",
    "garlic",
    "pork",
    "capers",
    "parsley",
    "lime",
    "fish sauce",
    "chili",
    "carrot",
    "mushroom",
    "tomato",
    "oregano",
    "green cardamom",
    "coriander seed",
    "cumin seed",
    "peppercorn",
    "clove",
    "fennel",
    "cinnamon",
    "anise",
    "nutmeg",
    "octopus",
    "strawberry",
    "crab",
    "guanciale",
    "cheese",
    "pasta",
    "cabbage",
    "canadian bacon",
    "lamb",
    "rib",
    "chicken",
    "teriyaki sauce",
    "pepper",
    "beans",
    "avocado",
    "onion",
    "bread",
    "herbs",
    "pumpkin",
    "butter",
    "turkey",
    "sesame oil",
    "new potatoes",
    "rhubarb",
    "wine",
    "corn"
]

const CUISINE_TYPES = [
    'american',
    'asian',
    'british',
    'caribbean',
    'central europe',
    'chinese',
    'eastern europe',
    'french',
    'india',
    'italian',
    'japanese',
    'kosher',
    'mediterranean',
    'mexican',
    'middle eastern',
    'nordic',
    'south american',
    'south east asian'
]

const HEALTH_LABELS = [
    "Alcohol-Cocktail",
    "Alcohol-Free",
    "Celery-Free",
    "Crustcean-Free",
    "Dairy-Free",
    "DASH",
    "Egg-Free",
    "Fish-Free",
    "FODMAP-Free",
    "Gluten-Free",
    "Immuno-Supportive",
    "Keto-Friendly",
    "Kidney-Friendly",
    "Kosher",
    "Low Potassium",
    "Low Sugar",
    "Lupine-Free",
    "Mediterranean",
    "Mollusk-Free",
    "Mustard-Free",
    "No oil added",
    "Paleo",
    "Peanut-Free",
    "Pescatarian",
    "Pork-Free",
    "Red-Meat-Free",
    "Sesame-Free",
    "Shellfish-Free",
    "Soy-Free",
    "Sugar-Conscious",
    "Sulfite-Free",
    "Tree-Nut-Free",
    "Vegan",
    "Vegetarian",
    "Wheat-Free"
]

module.exports = {
    INGREDIENTS,
    HEALTH_LABELS,
    CUISINE_TYPES
}
